#!/system/bin/sh
#Copyright (c) 2012
#Seth Shelnutt

ln -s /firmware/image/acdb.mbn /system/etc/firmware/
ln -s /firmware/image/apps.mbn /system/etc/firmware/
ln -s /firmware/image/dsp1.mbn /system/etc/firmware/
ln -s /firmware/image/dsp2.mbn /system/etc/firmware/
ln -s /firmware/image/dsp3.mbn /system/etc/firmware/
ln -s /firmware/image/dsps.b00 /system/etc/firmware/
ln -s /firmware/image/dsps.b01 /system/etc/firmware/
ln -s firmware/image/dsps.b02 /system/etc/firmware/
ln -s /firmware/image/dsps.b03 /system/etc/firmware/
ln -s /firmware/image/dsps.b04 /system/etc/firmware/
ln -s /firmware/image/dsps.b05 /system/etc/firmware/
ln -s /firmware/image/dsps.mdt /system/etc/firmware/
ln -s /firmware/image/dxhdcp2.b00 /system/etc/firmware/
ln -s /firmware/image/dxhdcp2.b01 /system/etc/firmware/
ln -s /firmware/image/dxhdcp2.b02 /system/etc/firmware/
ln -s /firmware/image/dxhdcp2.b03 /system/etc/firmware/
ln -s /firmware/image/dxhdcp2.mdt /system/etc/firmware/
ln -s /firmware/image/efs1.mbn /system/etc/firmware/
ln -s /firmware/image/efs2.mbn /system/etc/firmware/
ln -s /firmware/image/efs3.mbn /system/etc/firmware/
ln -s /firmware/image/mdm_acdb.img /system/etc/firmware/
ln -s /firmware/image/q6.b00 /system/etc/firmware/
ln -s /firmware/image/q6.b01 /system/etc/firmware/
ln -s /firmware/image/q6.b03 /system/etc/firmware/
ln -s /firmware/image/q6.b04 /system/etc/firmware/
ln -s /firmware/image/q6.b05 /system/etc/firmware/
ln -s /firmware/image/q6.b06 /system/etc/firmware/
ln -s /firmware/image/q6.mdt /system/etc/firmware/
ln -s /firmware/image/rpm.mbn /system/etc/firmware/
ln -s /firmware/image/sampleap.b00 /system/etc/firmware/
ln -s /firmware/image/sampleap.b01 /system/etc/firmware/
ln -s /firmware/image/sampleap.b02 /system/etc/firmware/
ln -s /firmware/image/sampleap.b03 /system/etc/firmware/
ln -s /firmware/image/sampleap.mdt /system/etc/firmware/
ln -s /firmware/image/sbl1.mbn /system/etc/firmware/
ln -s /firmware/image/sbl2.mbn /system/etc/firmware/
ln -s /firmware/image/tzapps.b00 /system/etc/firmware/
ln -s /firmware/image/tzapps.b01 /system/etc/firmware/
ln -s /firmware/image/tzapps.b02 /system/etc/firmware/
ln -s /firmware/image/tzapps.b03 /system/etc/firmware/
ln -s /firmware/image/tzapps.mdt /system/etc/firmware/
ln -s /firmware/image/wcnss.b00 /system/etc/firmware/
ln -s /firmware/image/wcnss.b01 /system/etc/firmware/
ln -s /firmware/image/wcnss.b02 /system/etc/firmware/
ln -s /firmware/image/wcnss.b04 /system/etc/firmware/
ln -s /firmware/image/wcnss.b05 /system/etc/firmware/
ln -s /firmware/image/wcnss.mdt /system/etc/firmware/
